"""initial schema

Revision ID: 0b4cd4c5a067
Revises: 
Create Date: 2026-03-26 11:51:49.497418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4cd4c5a067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=False),
    sa.Column('internal_code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_internal_code'), ['internal_code'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'FINALIZADA', 'CANCELADA', name='collection_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    op.create_table('stock_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_SEPARACAO', 'PRONTO', 'ENTREGUE', 'CANCELADO', name='stock_request_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_requests_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_requests_status'), ['status'], unique=False)

    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('scanned_code', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_scanned_code'), ['scanned_code'], unique=False)

    op.create_table('request_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_request_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDENTE', 'EM_SEPARACAO', 'PRONTO', 'ENTREGUE', 'CANCELADO', name='stock_request_status'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDENTE', 'EM_SEPARACAO', 'PRONTO', 'ENTREGUE', 'CANCELADO', name='stock_request_status'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_request_id'], ['stock_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_status_history_changed_by_user_id'), ['changed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_status_history_new_status'), ['new_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_status_history_stock_request_id'), ['stock_request_id'], unique=False)

    op.create_table('stock_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_request_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('scanned_code', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_request_id'], ['stock_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_request_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_request_items_scanned_code'), ['scanned_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_request_items_stock_request_id'), ['stock_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_request_items_stock_request_id'))
        batch_op.drop_index(batch_op.f('ix_stock_request_items_scanned_code'))
        batch_op.drop_index(batch_op.f('ix_stock_request_items_product_id'))

    op.drop_table('stock_request_items')
    with op.batch_alter_table('request_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_status_history_stock_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_status_history_new_status'))
        batch_op.drop_index(batch_op.f('ix_request_status_history_changed_by_user_id'))

    op.drop_table('request_status_history')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_scanned_code'))
        batch_op.drop_index(batch_op.f('ix_collection_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_collection_items_collection_id'))

    op.drop_table('collection_items')
    with op.batch_alter_table('stock_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_requests_status'))
        batch_op.drop_index(batch_op.f('ix_stock_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_requests_branch_id'))

    op.drop_table('stock_requests')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))
        batch_op.drop_index(batch_op.f('ix_collections_status'))
        batch_op.drop_index(batch_op.f('ix_collections_branch_id'))

    op.drop_table('collections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_branch_id'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_slug'))

    op.drop_table('roles')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_internal_code'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_code'))

    op.drop_table('branches')
    # ### end Alembic commands ###
